# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.accounts_and_cards_account_and_card_behavior_api import AccountsAndCardsAccountAndCardBehaviorApi


class TestAccountsAndCardsAccountAndCardBehaviorApi(unittest.TestCase):
    """AccountsAndCardsAccountAndCardBehaviorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountsAndCardsAccountAndCardBehaviorApi()

    def tearDown(self) -> None:
        pass

    def test_get_account_features_post(self) -> None:
        """Test case for get_account_features_post

        Get Account Features
        """
        pass

    def test_modify_status_post(self) -> None:
        """Test case for modify_status_post

        Modify Status
        """
        pass

    def test_set_account_feature_post(self) -> None:
        """Test case for set_account_feature_post

        Set Account Feature
        """
        pass


if __name__ == '__main__':
    unittest.main()
