# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.transactions_ach_api import TransactionsAchApi


class TestTransactionsAchApi(unittest.TestCase):
    """TransactionsAchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionsAchApi()

    def tearDown(self) -> None:
        pass

    def test_add_ach_account_corporate_post(self) -> None:
        """Test case for add_ach_account_corporate_post

        Add ACH Account Corporate
        """
        pass

    def test_add_ach_account_post(self) -> None:
        """Test case for add_ach_account_post

        Add ACH Account
        """
        pass

    def test_cancel_ach_transaction_post(self) -> None:
        """Test case for cancel_ach_transaction_post

        Cancel ACH Transaction
        """
        pass

    def test_cancel_simulated_ach_transaction_post(self) -> None:
        """Test case for cancel_simulated_ach_transaction_post

        Cancel Simulated Incoming ACH Transaction
        """
        pass

    def test_create_ach_transaction_post(self) -> None:
        """Test case for create_ach_transaction_post

        Create ACH Transaction
        """
        pass

    def test_create_simulated_ach_transaction_post(self) -> None:
        """Test case for create_simulated_ach_transaction_post

        Create Simulated Incoming ACH Transaction
        """
        pass

    def test_get_ach_accounts_post(self) -> None:
        """Test case for get_ach_accounts_post

        Get ACH Accounts
        """
        pass

    def test_get_ach_trans_history_post(self) -> None:
        """Test case for get_ach_trans_history_post

        Get ACH Transaction History
        """
        pass

    def test_get_all_simulated_ach_transactions_post(self) -> None:
        """Test case for get_all_simulated_ach_transactions_post

        Get All Simulated Incoming ACH Transactions
        """
        pass

    def test_get_deposit_history_post(self) -> None:
        """Test case for get_deposit_history_post

        Get Deposit History
        """
        pass

    def test_get_pending_deposits_post(self) -> None:
        """Test case for get_pending_deposits_post

        Get Pending Deposits
        """
        pass

    def test_get_simulated_ach_transaction_post(self) -> None:
        """Test case for get_simulated_ach_transaction_post

        Get Simulated Incoming ACH Transaction
        """
        pass

    def test_modify_ach_account_post(self) -> None:
        """Test case for modify_ach_account_post

        Modify ACH Account
        """
        pass

    def test_modify_pending_deposit_status_post(self) -> None:
        """Test case for modify_pending_deposit_status_post

        Modify Pending Deposit Status
        """
        pass

    def test_remove_ach_account_post(self) -> None:
        """Test case for remove_ach_account_post

        Remove ACH Account
        """
        pass


if __name__ == '__main__':
    unittest.main()
