# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.miscellaneous_api import MiscellaneousApi


class TestMiscellaneousApi(unittest.TestCase):
    """MiscellaneousApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MiscellaneousApi()

    def tearDown(self) -> None:
        pass

    def test_get_call_status_post(self) -> None:
        """Test case for get_call_status_post

        Get Call Status
        """
        pass

    def test_get_ingo_customer_id_post(self) -> None:
        """Test case for get_ingo_customer_id_post

        Get Ingo Customer ID
        """
        pass

    def test_get_product_info_post(self) -> None:
        """Test case for get_product_info_post

        Get Product Info
        """
        pass

    def test_get_promontory_bank_list_post(self) -> None:
        """Test case for get_promontory_bank_list_post

        Get Promontory Bank List
        """
        pass

    def test_ping_post(self) -> None:
        """Test case for ping_post

        Ping
        """
        pass


if __name__ == '__main__':
    unittest.main()
