# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.accounts_and_cards_enrollment_api import AccountsAndCardsEnrollmentApi


class TestAccountsAndCardsEnrollmentApi(unittest.TestCase):
    """AccountsAndCardsEnrollmentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountsAndCardsEnrollmentApi()

    def tearDown(self) -> None:
        pass

    def test_complete_enrollment_post(self) -> None:
        """Test case for complete_enrollment_post

        Complete Enrollment
        """
        pass

    def test_create_account_post(self) -> None:
        """Test case for create_account_post

        Create Account
        """
        pass

    def test_create_virtual_card_post(self) -> None:
        """Test case for create_virtual_card_post

        Create Virtual Card Account
        """
        pass

    def test_force_pass_cip_post(self) -> None:
        """Test case for force_pass_cip_post

        Force Pass CIP
        """
        pass

    def test_get_enrollment_info_post(self) -> None:
        """Test case for get_enrollment_info_post

        Get Enrollment Info
        """
        pass

    def test_run_cip_post(self) -> None:
        """Test case for run_cip_post

        Run CIP
        """
        pass

    def test_run_enrollment_cip_post(self) -> None:
        """Test case for run_enrollment_cip_post

        Run Enrollment CIP
        """
        pass

    def test_start_enrollment_post(self) -> None:
        """Test case for start_enrollment_post

        Start Enrollment
        """
        pass

    def test_update_enrollment_post(self) -> None:
        """Test case for update_enrollment_post

        Update Enrollment
        """
        pass

    def test_verify_enrollment_post(self) -> None:
        """Test case for verify_enrollment_post

        Verify Enrollment
        """
        pass


if __name__ == '__main__':
    unittest.main()
