# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.accounts_and_cards_account_management_api import AccountsAndCardsAccountManagementApi


class TestAccountsAndCardsAccountManagementApi(unittest.TestCase):
    """AccountsAndCardsAccountManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountsAndCardsAccountManagementApi()

    def tearDown(self) -> None:
        pass

    def test_add_account_post(self) -> None:
        """Test case for add_account_post

        Add Account
        """
        pass

    def test_charge_off_account_post(self) -> None:
        """Test case for charge_off_account_post

        Charge Off Account
        """
        pass

    def test_get_account_by_id_post(self) -> None:
        """Test case for get_account_by_id_post

        Get Account by ID
        """
        pass

    def test_get_balance_post(self) -> None:
        """Test case for get_balance_post

        Get Balance
        """
        pass

    def test_get_related_accounts_post(self) -> None:
        """Test case for get_related_accounts_post

        Get Related Accounts
        """
        pass

    def test_get_roundup_accounts_post(self) -> None:
        """Test case for get_roundup_accounts_post

        Get Roundup Accounts
        """
        pass

    def test_get_savings_interest_post(self) -> None:
        """Test case for get_savings_interest_post

        Get Savings Interest
        """
        pass

    def test_get_user_defined_account_fields_post(self) -> None:
        """Test case for get_user_defined_account_fields_post

        Get User-Defined Account Fields
        """
        pass

    def test_recover_charged_off_account_post(self) -> None:
        """Test case for recover_charged_off_account_post

        Recover Charged-Off Account
        """
        pass

    def test_search_accounts_post(self) -> None:
        """Test case for search_accounts_post

        Search Accounts
        """
        pass

    def test_set_roundup_accounts_post(self) -> None:
        """Test case for set_roundup_accounts_post

        Set Roundup Accounts
        """
        pass

    def test_set_user_defined_account_field_post(self) -> None:
        """Test case for set_user_defined_account_field_post

        Set User-Defined Account Field
        """
        pass

    def test_switch_product_post(self) -> None:
        """Test case for switch_product_post

        Switch Product
        """
        pass

    def test_update_account_post(self) -> None:
        """Test case for update_account_post

        Update Account
        """
        pass

    def test_verify_account_post(self) -> None:
        """Test case for verify_account_post

        Verify Account
        """
        pass


if __name__ == '__main__':
    unittest.main()
