# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.accounts_and_cards_card_management_api import AccountsAndCardsCardManagementApi


class TestAccountsAndCardsCardManagementApi(unittest.TestCase):
    """AccountsAndCardsCardManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountsAndCardsCardManagementApi()

    def tearDown(self) -> None:
        pass

    def test_activate_card_post(self) -> None:
        """Test case for activate_card_post

        Activate Card
        """
        pass

    def test_add_card_post(self) -> None:
        """Test case for add_card_post

        Add Card
        """
        pass

    def test_commit_card_pin_change_post(self) -> None:
        """Test case for commit_card_pin_change_post

        Commit Card PIN Change
        """
        pass

    def test_create_provisioning_request_post(self) -> None:
        """Test case for create_provisioning_request_post

        Create Provisioning Request
        """
        pass

    def test_get_access_token_post(self) -> None:
        """Test case for get_access_token_post

        Get Access Token
        """
        pass

    def test_get_account_cards_post(self) -> None:
        """Test case for get_account_cards_post

        Get Account Cards
        """
        pass

    def test_get_card_pin_change_key_post(self) -> None:
        """Test case for get_card_pin_change_key_post

        Get Card PIN-Change Key
        """
        pass

    def test_get_card_post(self) -> None:
        """Test case for get_card_post

        Get Card
        """
        pass

    def test_get_interest_post(self) -> None:
        """Test case for get_interest_post

        Get Interest
        """
        pass

    def test_reissue_card_post(self) -> None:
        """Test case for reissue_card_post

        Reissue Card
        """
        pass

    def test_replace_lost_stolen_card_post(self) -> None:
        """Test case for replace_lost_stolen_card_post

        Replace Lost Stolen Card
        """
        pass

    def test_reset_card_pin_fail_count_post(self) -> None:
        """Test case for reset_card_pin_fail_count_post

        Reset Card PIN-Fail Count
        """
        pass

    def test_verify_card_security_code_post(self) -> None:
        """Test case for verify_card_security_code_post

        Verify Card Security Code
        """
        pass

    def test_void_add_card_post(self) -> None:
        """Test case for void_add_card_post

        Void Add Card
        """
        pass


if __name__ == '__main__':
    unittest.main()
