# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.transactions_account_to_account_api import TransactionsAccountToAccountApi


class TestTransactionsAccountToAccountApi(unittest.TestCase):
    """TransactionsAccountToAccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionsAccountToAccountApi()

    def tearDown(self) -> None:
        pass

    def test_create_account_transfer_post(self) -> None:
        """Test case for create_account_transfer_post

        Create Account Transfer
        """
        pass

    def test_reverse_account_transfer_post(self) -> None:
        """Test case for reverse_account_transfer_post

        Reverse Account Transfer
        """
        pass


if __name__ == '__main__':
    unittest.main()
