# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.alerts_api import AlertsApi


class TestAlertsApi(unittest.TestCase):
    """AlertsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AlertsApi()

    def tearDown(self) -> None:
        pass

    def test_get_alerts_blackout_post(self) -> None:
        """Test case for get_alerts_blackout_post

        Get Alerts Blackout
        """
        pass

    def test_get_alerts_post(self) -> None:
        """Test case for get_alerts_post

        Get Alerts
        """
        pass

    def test_get_carrier_list_post(self) -> None:
        """Test case for get_carrier_list_post

        Get Carriers List
        """
        pass

    def test_modify_on_demand_alert_status_post(self) -> None:
        """Test case for modify_on_demand_alert_status_post

        Modify On-Demand Alert Status
        """
        pass

    def test_set_alerts_blackout_post(self) -> None:
        """Test case for set_alerts_blackout_post

        Set Alerts Blackout
        """
        pass

    def test_set_alerts_post(self) -> None:
        """Test case for set_alerts_post

        Set Alerts
        """
        pass

    def test_verify_on_demand_alert_status_post(self) -> None:
        """Test case for verify_on_demand_alert_status_post

        Verify On-Demand Alert Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
