# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.instant_issue_api import InstantIssueApi


class TestInstantIssueApi(unittest.TestCase):
    """InstantIssueApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InstantIssueApi()

    def tearDown(self) -> None:
        pass

    def test_create_bulk_card_order_post(self) -> None:
        """Test case for create_bulk_card_order_post

        Create Bulk Card Order
        """
        pass

    def test_get_bulk_card_order_post(self) -> None:
        """Test case for get_bulk_card_order_post

        Get Bulk Card Order
        """
        pass

    def test_get_load_locations_post(self) -> None:
        """Test case for get_load_locations_post

        Get Load Locations
        """
        pass

    def test_move_card_inventory_post(self) -> None:
        """Test case for move_card_inventory_post

        Move Card Inventory
        """
        pass

    def test_move_card_post(self) -> None:
        """Test case for move_card_post

        Move Card
        """
        pass

    def test_verify_instant_issue_card_post(self) -> None:
        """Test case for verify_instant_issue_card_post

        Verify Instant-Issue Card
        """
        pass


if __name__ == '__main__':
    unittest.main()
