# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.location_management_api import LocationManagementApi


class TestLocationManagementApi(unittest.TestCase):
    """LocationManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LocationManagementApi()

    def tearDown(self) -> None:
        pass

    def test_create_location_fee_post(self) -> None:
        """Test case for create_location_fee_post

        Create Location Fee
        """
        pass

    def test_create_location_post(self) -> None:
        """Test case for create_location_post

        Create Location
        """
        pass

    def test_get_locations_post(self) -> None:
        """Test case for get_locations_post

        Get Locations
        """
        pass

    def test_modify_location_fee_post(self) -> None:
        """Test case for modify_location_fee_post

        Modify Location Fee
        """
        pass

    def test_modify_location_post(self) -> None:
        """Test case for modify_location_post

        Modify Location
        """
        pass


if __name__ == '__main__':
    unittest.main()
