# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.corporate_hierarchy_api import CorporateHierarchyApi


class TestCorporateHierarchyApi(unittest.TestCase):
    """CorporateHierarchyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CorporateHierarchyApi()

    def tearDown(self) -> None:
        pass

    def test_create_group_post(self) -> None:
        """Test case for create_group_post

        Create Group
        """
        pass

    def test_delete_groups_post(self) -> None:
        """Test case for delete_groups_post

        Delete Groups
        """
        pass

    def test_get_account_group_relationships_post(self) -> None:
        """Test case for get_account_group_relationships_post

        Get Account Group Relationships
        """
        pass

    def test_get_group_hierarchy_post(self) -> None:
        """Test case for get_group_hierarchy_post

        Get Group Hierarchy
        """
        pass

    def test_get_groups_info_post(self) -> None:
        """Test case for get_groups_info_post

        Get Groups Info
        """
        pass

    def test_get_root_groups_post(self) -> None:
        """Test case for get_root_groups_post

        Get Root Groups
        """
        pass

    def test_remove_account_group_relationship_post(self) -> None:
        """Test case for remove_account_group_relationship_post

        Remove Account Group Relationship
        """
        pass

    def test_set_account_group_relationships_post(self) -> None:
        """Test case for set_account_group_relationships_post

        Set Account Group Relationships
        """
        pass

    def test_update_group_post(self) -> None:
        """Test case for update_group_post

        Update Group
        """
        pass


if __name__ == '__main__':
    unittest.main()
