# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.credit_api import CreditApi


class TestCreditApi(unittest.TestCase):
    """CreditApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CreditApi()

    def tearDown(self) -> None:
        pass

    def test_get_auto_pay_history_post(self) -> None:
        """Test case for get_auto_pay_history_post

        Get Auto Pay History
        """
        pass

    def test_get_credit_limit_change_history_post(self) -> None:
        """Test case for get_credit_limit_change_history_post

        Get Credit Limit Change History
        """
        pass

    def test_get_credit_summary_post(self) -> None:
        """Test case for get_credit_summary_post

        Get Credit Summary
        """
        pass

    def test_set_auto_pay_attempt_post(self) -> None:
        """Test case for set_auto_pay_attempt_post

        Set Auto Pay Attempt
        """
        pass

    def test_set_auto_pay_plan_post(self) -> None:
        """Test case for set_auto_pay_plan_post

        Set Auto Pay Plan
        """
        pass

    def test_set_credit_limit_post(self) -> None:
        """Test case for set_credit_limit_post

        Set Credit Limit
        """
        pass


if __name__ == '__main__':
    unittest.main()
