# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.transactions_bill_payments_api import TransactionsBillPaymentsApi


class TestTransactionsBillPaymentsApi(unittest.TestCase):
    """TransactionsBillPaymentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionsBillPaymentsApi()

    def tearDown(self) -> None:
        pass

    def test_add_paper_biller_post(self) -> None:
        """Test case for add_paper_biller_post

        Add Paper Biller
        """
        pass

    def test_add_rpps_biller_post(self) -> None:
        """Test case for add_rpps_biller_post

        Add RPPS Biller
        """
        pass

    def test_cancel_bill_payment_post(self) -> None:
        """Test case for cancel_bill_payment_post

        Cancel Bill Payment
        """
        pass

    def test_create_bill_payment_post(self) -> None:
        """Test case for create_bill_payment_post

        Create Bill Payment
        """
        pass

    def test_get_bill_pay_history_post(self) -> None:
        """Test case for get_bill_pay_history_post

        Get Bill Payment History
        """
        pass

    def test_get_billers_post(self) -> None:
        """Test case for get_billers_post

        Get Billers
        """
        pass

    def test_get_scheduled_bill_payments_post(self) -> None:
        """Test case for get_scheduled_bill_payments_post

        Get Scheduled Bill Payments
        """
        pass

    def test_modify_paper_biller_post(self) -> None:
        """Test case for modify_paper_biller_post

        Modify Paper Biller
        """
        pass

    def test_modify_rpps_biller_post(self) -> None:
        """Test case for modify_rpps_biller_post

        Modify RPPS Biller
        """
        pass

    def test_remove_biller_post(self) -> None:
        """Test case for remove_biller_post

        Remove Biller
        """
        pass

    def test_search_biller_directory_post(self) -> None:
        """Test case for search_biller_directory_post

        Search Biller Directory
        """
        pass


if __name__ == '__main__':
    unittest.main()
