# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.federal_benefit_enrollment_api import FederalBenefitEnrollmentApi


class TestFederalBenefitEnrollmentApi(unittest.TestCase):
    """FederalBenefitEnrollmentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FederalBenefitEnrollmentApi()

    def tearDown(self) -> None:
        pass

    def test_create_fb_enrollment_post(self) -> None:
        """Test case for create_fb_enrollment_post

        Create Federal Benefit Enrollment
        """
        pass

    def test_get_fb_enrollments_post(self) -> None:
        """Test case for get_fb_enrollments_post

        Get Federal Benefit Enrollments
        """
        pass

    def test_resubmit_fb_enrollment_post(self) -> None:
        """Test case for resubmit_fb_enrollment_post

        Resubmit Federal Benefit Enrollment
        """
        pass

    def test_update_fb_enrollment_post(self) -> None:
        """Test case for update_fb_enrollment_post

        Update Federal Benefit Enrollment
        """
        pass


if __name__ == '__main__':
    unittest.main()
