# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.transactions_fees_api import TransactionsFeesApi


class TestTransactionsFeesApi(unittest.TestCase):
    """TransactionsFeesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionsFeesApi()

    def tearDown(self) -> None:
        pass

    def test_assess_fee_post(self) -> None:
        """Test case for assess_fee_post

        Assess Fee
        """
        pass

    def test_get_fee_history_post(self) -> None:
        """Test case for get_fee_history_post

        Get Fee History
        """
        pass

    def test_get_fee_summary_post(self) -> None:
        """Test case for get_fee_summary_post

        Get Fee Summary
        """
        pass

    def test_get_pending_fees_post(self) -> None:
        """Test case for get_pending_fees_post

        Get Pending Fees
        """
        pass

    def test_reverse_fee_post(self) -> None:
        """Test case for reverse_fee_post

        Reverse Fee
        """
        pass


if __name__ == '__main__':
    unittest.main()
