# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.overdraft_api import OverdraftApi


class TestOverdraftApi(unittest.TestCase):
    """OverdraftApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OverdraftApi()

    def tearDown(self) -> None:
        pass

    def test_get_overdraft_balance_post(self) -> None:
        """Test case for get_overdraft_balance_post

        Get Overdraft Balance
        """
        pass


if __name__ == '__main__':
    unittest.main()
