# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.corporate_credit_and_rtf_api import CorporateCreditAndRTFApi


class TestCorporateCreditAndRTFApi(unittest.TestCase):
    """CorporateCreditAndRTFApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CorporateCreditAndRTFApi()

    def tearDown(self) -> None:
        pass

    def test_get_corporate_credit_change_history_post(self) -> None:
        """Test case for get_corporate_credit_change_history_post

        Get Corporate Credit Change History
        """
        pass

    def test_get_corporate_credit_summary_post(self) -> None:
        """Test case for get_corporate_credit_summary_post

        Get Corporate Credit Summary
        """
        pass

    def test_is_corp_credit_funding_account_post(self) -> None:
        """Test case for is_corp_credit_funding_account_post

        Is Corporate Credit Funding Account
        """
        pass

    def test_is_corp_credit_spending_account_post(self) -> None:
        """Test case for is_corp_credit_spending_account_post

        Is Corporate Credit Spending Account
        """
        pass

    def test_set_corporate_credit_limit_post(self) -> None:
        """Test case for set_corporate_credit_limit_post

        Set Corporate Credit Limit
        """
        pass


if __name__ == '__main__':
    unittest.main()
