# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.transactions_adjustments_api import TransactionsAdjustmentsApi


class TestTransactionsAdjustmentsApi(unittest.TestCase):
    """TransactionsAdjustmentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionsAdjustmentsApi()

    def tearDown(self) -> None:
        pass

    def test_create_adjustment_post(self) -> None:
        """Test case for create_adjustment_post

        Create Adjustment
        """
        pass

    def test_reverse_adjustment_post(self) -> None:
        """Test case for reverse_adjustment_post

        Reverse Adjustment
        """
        pass


if __name__ == '__main__':
    unittest.main()
