# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.ivr_api import IVRApi


class TestIVRApi(unittest.TestCase):
    """IVRApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IVRApi()

    def tearDown(self) -> None:
        pass

    def test_create_ivr_call_post(self) -> None:
        """Test case for create_ivr_call_post

        Create IVR Call
        """
        pass

    def test_get_ivr_call_identifier_post(self) -> None:
        """Test case for get_ivr_call_identifier_post

        Get IVR Call Identifier
        """
        pass

    def test_get_ivr_call_status_post(self) -> None:
        """Test case for get_ivr_call_status_post

        Get IVR Call Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
