# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.accounts_and_cards_customer_notes_api import AccountsAndCardsCustomerNotesApi


class TestAccountsAndCardsCustomerNotesApi(unittest.TestCase):
    """AccountsAndCardsCustomerNotesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountsAndCardsCustomerNotesApi()

    def tearDown(self) -> None:
        pass

    def test_add_customer_note_post(self) -> None:
        """Test case for add_customer_note_post

        Add Customer Note
        """
        pass

    def test_get_customer_note_history_post(self) -> None:
        """Test case for get_customer_note_history_post

        Get Customer Note History
        """
        pass


if __name__ == '__main__':
    unittest.main()
