# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.transactions_payments_api import TransactionsPaymentsApi


class TestTransactionsPaymentsApi(unittest.TestCase):
    """TransactionsPaymentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionsPaymentsApi()

    def tearDown(self) -> None:
        pass

    def test_create_payment_post(self) -> None:
        """Test case for create_payment_post

        Create Payment
        """
        pass

    def test_get_payment_history_post(self) -> None:
        """Test case for get_payment_history_post

        Get Payment History
        """
        pass

    def test_reverse_payment_post(self) -> None:
        """Test case for reverse_payment_post

        Reverse Payment
        """
        pass

    def test_update_payment_post(self) -> None:
        """Test case for update_payment_post

        Update Payment
        """
        pass


if __name__ == '__main__':
    unittest.main()
