# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.account_level_controls_api import AccountLevelControlsApi


class TestAccountLevelControlsApi(unittest.TestCase):
    """AccountLevelControlsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountLevelControlsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_account_level_auth_control_post(self) -> None:
        """Test case for delete_account_level_auth_control_post

        Delete Account Level Auth Control
        """
        pass

    def test_delete_account_level_mcc_control_post(self) -> None:
        """Test case for delete_account_level_mcc_control_post

        Delete Account Level MCC Control
        """
        pass

    def test_delete_account_level_merchant_control_post(self) -> None:
        """Test case for delete_account_level_merchant_control_post

        Delete Account Level Merchant Control
        """
        pass

    def test_get_auth_control_post(self) -> None:
        """Test case for get_auth_control_post

        Get Auth Control
        """
        pass

    def test_get_mcc_controls_post(self) -> None:
        """Test case for get_mcc_controls_post

        Get MCC Controls
        """
        pass

    def test_get_merchant_controls_post(self) -> None:
        """Test case for get_merchant_controls_post

        Get Merchant Controls
        """
        pass

    def test_set_account_level_auth_control_post(self) -> None:
        """Test case for set_account_level_auth_control_post

        Set Account-Level Auth Control 
        """
        pass

    def test_set_account_level_mcc_control_post(self) -> None:
        """Test case for set_account_level_mcc_control_post

        Set Account-Level MCC Control
        """
        pass

    def test_set_account_level_merchant_control_post(self) -> None:
        """Test case for set_account_level_merchant_control_post

        Set Account-Level Merchant Control
        """
        pass


if __name__ == '__main__':
    unittest.main()
