# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.transactions_association_transactions_api import TransactionsAssociationTransactionsApi


class TestTransactionsAssociationTransactionsApi(unittest.TestCase):
    """TransactionsAssociationTransactionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionsAssociationTransactionsApi()

    def tearDown(self) -> None:
        pass

    def test_create_simulated_card_auth_post(self) -> None:
        """Test case for create_simulated_card_auth_post

        Create Simulated Card Authorization
        """
        pass

    def test_create_simulated_card_settle_post(self) -> None:
        """Test case for create_simulated_card_settle_post

        Create Simulated Card Settlement
        """
        pass

    def test_expire_authorization_post(self) -> None:
        """Test case for expire_authorization_post

        Expire Authorization
        """
        pass

    def test_get_auth_history_post(self) -> None:
        """Test case for get_auth_history_post

        Get Authorization History
        """
        pass

    def test_get_pending_merchant_credits_post(self) -> None:
        """Test case for get_pending_merchant_credits_post

        Get Pending Merchant Credits
        """
        pass

    def test_update_pending_merchant_credit_post(self) -> None:
        """Test case for update_pending_merchant_credit_post

        Update Pending Merchant Credit
        """
        pass


if __name__ == '__main__':
    unittest.main()
