# coding: utf-8

"""
    Galileo Pro API Docs

    Galileo Pro Program API

    The version of the OpenAPI document: 1.0.0
    Contact: luis.reis@trustly.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.transactions_transaction_history_api import TransactionsTransactionHistoryApi


class TestTransactionsTransactionHistoryApi(unittest.TestCase):
    """TransactionsTransactionHistoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionsTransactionHistoryApi()

    def tearDown(self) -> None:
        pass

    def test_get_account_overview_post(self) -> None:
        """Test case for get_account_overview_post

        Get Account Overview
        """
        pass

    def test_get_all_trans_history_post(self) -> None:
        """Test case for get_all_trans_history_post

        Get All Transaction History
        """
        pass

    def test_get_trans_history_post(self) -> None:
        """Test case for get_trans_history_post

        Get Transaction History
        """
        pass


if __name__ == '__main__':
    unittest.main()
